-
  name: Test Connectivity
  hosts: db_and_web_server1
  vars:
    ansible_ssh_pass: "{{ lookup('csvfile', 'db_and_web_server1 file=credentials.csv delimiter=,') }}"
    # ansible_ssh_pass: "{{ lookup('ini', 'password section=db_and_web_server1 file=credentials.ini') }}"
  tasks:
  - name: Ping target host
    ping:
      data: "Test"