---
- name: Deploy a web application
  hosts: db_and_web_server1, db_and_web_server2
  tasks:
    - name: Install dependencies
      apt: name={{ item }} state=present
      with_items:
       - python
       - python-setuptools
       - python-dev
       - build-essential
       - python-pip
       - python-mysqldb
      
    - import: tasks/deploy_db.yml
    - import: tasks/deploy_web.yml

